apiVersion: v2
appVersion: 1.1.0
description: A Helm chart for deploying kubetally
home: https://avesha.io/products/product-slice
icon: https://avatars.githubusercontent.com/u/99859346?s=200&v=4
keywords:
- multicloud
- multi cloud
- multitenant
- multitenancy
- multi tenant
- multi tenancy
- federated mesh
- federated clusters
- federated k8s
- federated kubernetes
- cluster sprawl
- sprawl
- namespace sprawl
- network policy
- overlay network
- mesh network
- security
- networking
- infrastructure
- application
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: support@aveshasystems.com
  name: Avesha
name: kubetally
type: application
version: 1.1.0
