global:
  imageRegistry: docker.io/aveshasystems
kubetally:
  pricingService:
    image: pricing-service
    tag: 1.8.0-RELEASE-2aa8a633
    imagePullPolicy: Always
  chargeUpdater:
    image: price-updater
    tag: 1.4.0
    imagePullPolicy: IfNotPresent
  kubeTallyReport:
    image: kubetally-report
    tag: latest-feature-gpu-cost
    imagePullPolicy: Always
  imagePullSecretName: kubeslice-image-pull-secret
