---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeslice-ui-v2
  name: kubeslice-ui-v2
  namespace: kubeslice-controller
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: kubeslice-ui-v2
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeslice-ui-v2
  namespace: kubeslice-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeslice-ui-v2
  template:
    metadata:
      labels:
        app: kubeslice-ui-v2
    spec:
      containers:
        - image: '{{ .Values.kubeslice.uiv2.imageRegistry }}/{{ .Values.kubeslice.uiv2.image }}:{{ .Values.kubeslice.uiv2.tag }}'
          imagePullPolicy: '{{ .Values.kubeslice.uiv2.pullPolicy }}'
          name: kubeslice-ui-v2
          securityContext:
            {{- with .Values.kubeslice.uiv2.containersecurityContext}}
            {{- toYaml . | nindent 10 }}
            {{- end }}
          ports:
            - containerPort: 8080
      {{- if .Values.imagePullSecretsName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretsName }}
      {{- end }}
      tolerations:
        - operator: "Exists"
      securityContext:
        {{- with .Values.kubeslice.uiv2.podsecurityContext }}
        {{- toYaml . | nindent 4 }}
        {{- end }} 