---
apiVersion: v1
kind: Service
metadata:
  name: kubeslice-ui-proxy
  labels:
    app: kubeslice-ui-proxy
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: http
      {{- if eq .Values.kubeslice.uiproxy.service.type "NodePort" }}
      nodePort: {{ .Values.kubeslice.uiproxy.service.nodePort }}
      {{ end }}
  {{- if .Values.kubeslice.uiproxy.labels }}
  selector:
    {{ toYaml .Values.kubeslice.uiproxy.labels | nindent 6 }}
  {{- end }}
  type: {{ .Values.kubeslice.uiproxy.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeslice-ui-proxy
spec:
  replicas: 1
  selector:
    {{- if .Values.kubeslice.uiproxy.labels }}
    matchLabels:
      {{ toYaml .Values.kubeslice.uiproxy.labels | nindent 8 }}
    {{- end }}
  template:
    metadata:
      {{- if .Values.kubeslice.uiproxy.labels }}
      labels: {{ toYaml .Values.kubeslice.uiproxy.labels | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: kubeslice-ui-proxy
          {{- if .Values.kubeslice.uiproxy.securityContext }}
          securityContext: {{ toYaml .Values.kubeslice.uiproxy.securityContext | nindent 12 }}
          {{- end }}
          image: '{{ .Values.kubeslice.uiproxy.imageRegistry }}/{{ .Values.kubeslice.uiproxy.image }}:{{ .Values.kubeslice.uiproxy.tag }}'
          imagePullPolicy: '{{ .Values.kubeslice.uiproxy.pullPolicy }}'
          env:
          - name: KUBESLICE-CONTROLLER-PROMETHEUS
            value: {{ .Values.kubeslice.prometheus.url }}
          - name: REACT_APP_SOCKET_URL
            value: 'ws://kubeslice-api-gw.kubeslice-controller.svc.cluster.local:3000'
          ports:
            - containerPort: 8443
      {{- if .Values.imagePullSecretsName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretsName }}
        {{- end }}
      {{- if .Values.kubeslice.uiproxy.tolerations }}
      tolerations: {{ toYaml .Values.kubeslice.uiproxy.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.kubeslice.uiproxy.securityContext }}
      securityContext: {{ toYaml .Values.kubeslice.uiproxy.securityContext | nindent 8 }}
      {{- end }}
