---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeslice-ui-v2
  name: kubeslice-ui-v2
  namespace: kubeslice-controller
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  {{- if .Values.kubeslice.uiv2.labels }}
  selector:
    {{ toYaml .Values.kubeslice.uiv2.labels | nindent 8 }}
  {{- end }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeslice-ui-v2
  namespace: kubeslice-controller
spec:
  replicas: 1
  selector:
    {{- if .Values.kubeslice.uiv2.labels }}
    matchLabels:
      {{ toYaml .Values.kubeslice.uiv2.labels | nindent 8 }}
    {{- end }}
  template:
    metadata:
      {{- if .Values.kubeslice.uiv2.labels }}
      labels: {{ toYaml .Values.kubeslice.uiv2.labels | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - image: '{{ .Values.kubeslice.uiv2.imageRegistry }}/{{ .Values.kubeslice.uiv2.image }}:{{ .Values.kubeslice.uiv2.tag }}'
          imagePullPolicy: '{{ .Values.kubeslice.uiv2.pullPolicy }}'
          name: kubeslice-ui-v2
          {{- if .Values.kubeslice.uiv2.securityContext }}
          securityContext: {{ toYaml .Values.kubeslice.uiv2.securityContext | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
      {{- if .Values.imagePullSecretsName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretsName }}
      {{- end }}
      {{- if .Values.kubeslice.uiv2.tolerations }}
      tolerations: {{ toYaml .Values.kubeslice.uiv2.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.kubeslice.uiv2.securityContext }}
      securityContext: {{ toYaml .Values.kubeslice.uiv2.securityContext | nindent 8 }}
      {{- end }}