---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.kubeslice.uiv2.labels }}
  labels:
  {{ toYaml .Values.kubeslice.uiv2.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.kubeslice.uiv2.annotations }}
  annotations:
  {{ toYaml .Values.kubeslice.uiv2.annotations | nindent 4 }}
  {{- end }}
  name: kubeslice-ui-v2
  namespace: kubeslice-controller
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    {{- if .Values.kubeslice.uiv2.labels }}
    {{ toYaml .Values.kubeslice.uiv2.labels | nindent 4 }}
    {{- end }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.kubeslice.uiv2.labels }}
  labels:
  {{ toYaml .Values.kubeslice.uiv2.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.kubeslice.uiv2.annotations }}
  annotations:
  {{ toYaml .Values.kubeslice.uiv2.annotations | nindent 4 }}
  {{- end }}
  name: kubeslice-ui-v2
  namespace: kubeslice-controller
spec:
  replicas: 1
  selector:
    matchLabels:
    {{- if .Values.kubeslice.uiv2.labels }}
    {{ toYaml .Values.kubeslice.uiv2.labels | nindent 6 }}
    {{- end }}
  template:
    metadata:
      annotations:
      {{- if .Values.kubeslice.uiv2.annotations }}
      {{ toYaml .Values.kubeslice.uiv2.annotations | nindent 8 }}
      {{- end }}
      {{- if .Values.kubeslice.uiv2.labels }}
      labels:
      {{ toYaml .Values.kubeslice.uiv2.labels | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.kubeslice.uiv2.affinity }}
      affinity:
      {{ toYaml .Values.kubeslice.uiv2.affinity | nindent 8 }}
      {{- end }}
      containers:
        - image: '{{ .Values.kubeslice.uiv2.imageRegistry }}/{{ .Values.kubeslice.uiv2.image }}:{{ .Values.kubeslice.uiv2.tag }}'
          imagePullPolicy: '{{ .Values.kubeslice.uiv2.pullPolicy }}'
          name: kubeslice-ui-v2
          {{- if .Values.kubeslice.uiv2.securityContext }}
          securityContext: {{ toYaml .Values.kubeslice.uiv2.securityContext | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
      {{- if .Values.imagePullSecretsName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretsName }}
      {{- end }}
      {{- if .Values.kubeslice.uiv2.tolerations }}
      tolerations: {{ toYaml .Values.kubeslice.uiv2.tolerations | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 65536               # Non-root user
        runAsGroup: 65536              # Non-root group
        runAsNonRoot: true             # Ensure the container does not run as root
        seccompProfile:
          type: RuntimeDefault