---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nsm-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/resource-policy": keep
    "helm.sh/hook-weight": "1"
data:
  excluded_prefixes_output.yaml: ''