# Mandatory Kubeconfig settings
global_kubeconfig: "/path/to/kubeconfig"
global_kubecontext: "my-cluster-context"

# Global default values (used unless overridden at the secret level)
global_controller_namespace: kubeslice-controller
global_project_namespace: kubeslice-avesha
global_role: Viewer
global_saName: kubeslice-rbac-ro-slice-andromeda
global_sliceName: devops
global_tokenTtlSeconds: 900
global_userName: Admin
global_validUntil: 2025-02-28


secrets:
  - name: secret-1
    apiKey: MGNlOGFkOWMtN2VkNi00YjYyLWFlNzAtN2U5MzlkZDVjNThh  # Secret-specific API key
    # Uses all global values for role, saName, sliceName, etc.

  - name: secret-2
    apiKey: ZjE3NDgxZjMtNTVlNy00YjI0LTk2ZTQtMTY1MzgzNGU3ODNk
    project_namespace: custom-namespace  # Overrides global_project_namespace
    sliceName: custom-slice              # Overrides global_sliceName

  - name: secret-3
    apiKey: YzNlNjQ3ZjgtOTQyZi00ZTkwLTg1OTgtZWM3M2M5NzJhZTFi
    role: Admin  # Overrides global_role
    tokenTtlSeconds: 1800  # Overrides global_tokenTtlSeconds
    userName: SuperUser  # Overrides global_userName
