# Mandatory Kubeconfig settings
global_kubeconfig: "./config.yaml"
global_kubecontext: "context-cveg5pviagq"

# Global default values (used unless overridden at the secret level)
global_controller_namespace: kubeslice-controller
global_project_namespace: kubeslice-avesha
global_role: Viewer
global_sliceName: devops
global_tokenTtlSeconds: 900
global_userName: Admin
global_validUntil: 2025-02-28


secrets:
  - name: secret-1
    role: Editor

  - name: secret-2

  - name: secret-3
    tokenTtlSeconds: 1800  # Overrides global_tokenTtlSeconds
    userName: SuperUser  # Overrides global_userName
