{{- $ca := genCA "gpr-admission-controller-ca" 3650 -}}
{{- $cn := printf "gpr-webhook-service" -}}
{{- $altName1 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc.cluster.local" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: gpr-admission-webhook-certs
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: gpr-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: gpr-controller-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: gpr-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
    - v1
  clientConfig:
    caBundle: {{ $ca.Cert | b64enc }}
    service:
      name: gpr-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-gpr-kubeslice-io-v1alpha1-gpuprovisioningrequest
  failurePolicy: Fail
  name: vgwebhook.kubeslice.io
  rules:
    - apiGroups:
        - gpr.kubeslice.io
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - gpuprovisioningrequests
  sideEffects: NoneOnDryRun
