apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-manager-access
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inventory-manager
  name: inventory-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inventory-manager-role
rules:
- apiGroups:
  - controller.kubeslice.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - controller.kubeslice.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - controller.kubeslice.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - inventory.kubeslice.io
  resources:
  - clustergpuallocations
  - workerclustergpuallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inventory.kubeslice.io
  resources:
  - clustergpuallocations/finalizers
  - workerclustergpuallocations/finalizers
  verbs:
  - update
- apiGroups:
  - inventory.kubeslice.io
  resources:
  - clustergpuallocations/status
  - workerclustergpuallocations/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inventory-metrics-auth-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inventory-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inventory-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: inventory-leader-election-role
subjects:
- kind: ServiceAccount
  name: inventory-manager-access
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inventory-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inventory-manager-role
subjects:
- kind: ServiceAccount
  name: inventory-manager-access
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inventory-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inventory-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: inventory-manager-access
  namespace: {{ .Release.Namespace }}
---