{{/*{{- define "controller.licensemode" -}}*/}}
  {{/*{{- $values := list "auto" "manual" "air-gap" -}}*/}}
  {{/*{{- if not (contains $values .) }}*/}}
  {{/*{{- fail (printf "Invalid value '%s' for license mode" .) -}}*/}}
  {{/*{{- end }}*/}}
  {{/*{{- . }}*/}}
  {{/*{{- end }}*/}}

  {{/*{{- define "controller.licensetype" -}}*/}}
  {{/*{{- $values := list "kubeslice-trial-license" -}}*/}}
  {{/*{{- if not (contains $values .) }}*/}}
  {{/*{{- fail (printf "Invalid value '%s' for license type" .) -}}*/}}
  {{/*{{- end }}*/}}
  {{/*{{- . }}*/}}
  {{/*{{- end }}*/}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeslice-controller-license-config
  namespace: kubeslice-controller
  labels:
    app.kubernetes.io/managed-by: kubeslice-controller
data:
  apiURL: LZtbEDBzFinn2HBQgc89vK8h2chsdurscRqbcvgzstvJ2zUR7cXL0d21Ik73br6vfE8aqZrROC41Zbf1Zj485W7OXHI=
  apiKey: szl3olNL5Sn0GrS3jbuLxZjTMw7ja1tmRXiyQtZMyFJL8kgC3tTBNNWaLyK7utqN63bStzvpgXM=
  publicKey: LQQxX1nN1iVGa2CAxidr1BgmsUIaWj0NtRnnKSX2DadGuENhLuo-5o7eczuINCM-bxPUPfNc_jwEinN2oBx_1cLYN3MewdXdETwxRUGAgZQ=
  maxSamples: Y9hz2m-_gUS3hMFpDTmhSO5A
  sampleInterval: 6jEhxl11PVq7GnELEgjUYtq2
binaryData: {}


