{{- if .Values.egs.metricsIngestion.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.egs.metricsIngestion.labels }}
  labels:
  {{ toYaml .Values.egs.metricsIngestion.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.egs.metricsIngestion.annotations }}
  annotations:
  {{ toYaml .Values.egs.metricsIngestion.annotations | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.egs.metricsIngestion.service.name }}
spec:
  replicas: {{ .Values.egs.metricsIngestion.replicas | default 1 }}
  {{- if .Values.egs.metricsIngestion.strategy }}
  strategy:
  {{ toYaml .Values.egs.metricsIngestion.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
    {{- if .Values.egs.metricsIngestion.labels }}
    {{ toYaml .Values.egs.metricsIngestion.labels | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- if .Values.egs.metricsIngestion.annotations }}
      annotations:
        {{ toYaml .Values.egs.metricsIngestion.annotations | nindent 8 }}
      {{- end }}
      {{- if .Values.egs.metricsIngestion.labels }}
      labels:
      {{ toYaml .Values.egs.metricsIngestion.labels | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.egs.metricsIngestion.affinity }}
      affinity:
      {{ toYaml .Values.egs.metricsIngestion.affinity | nindent 8 }}
      {{- end }}
      containers:
        - name: "ingestion"
          securityContext:
          {{- if .Values.egs.metricsIngestion.containerSecurityContext }}
          {{ toYaml .Values.egs.metricsIngestion.containerSecurityContext | nindent 12 }}
          {{- end }}
          image: '{{ .Values.egs.metricsIngestion.imageRegistry }}/{{ .Values.egs.metricsIngestion.image }}:{{ .Values.egs.metricsIngestion.tag }}'
          ports:
            - containerPort: 8080
              protocol: TCP
          {{- if .Values.egs.metricsIngestion.resources }}
          resources: {{ toYaml .Values.egs.metricsIngestion.resources | nindent 10 }}
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.egs.metricsIngestion.imagePullPolicy }}
          {{- if .Values.egs.metricsIngestion.env }}
          env:
          {{- range $key, $value := .Values.egs.metricsIngestion.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.egs.metricsIngestion.volumeMounts }}
          volumeMounts:
          {{ toYaml .Values.egs.metricsIngestion.volumeMounts | nindent 10 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
      {{- if .Values.egs.metricsIngestion.podSecurityContext }}
      {{ toYaml .Values.egs.metricsIngestion.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecretsName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretsName }}
      {{- end }}
      schedulerName: default-scheduler
      {{- if .Values.egs.metricsIngestion.tolerations }}
      tolerations: 
      {{ toYaml .Values.egs.metricsIngestion.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.egs.metricsIngestion.volumes }}
      volumes:
      {{ toYaml .Values.egs.metricsIngestion.volumes | nindent 8 }}
      {{- end }}
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
{{- end }}
---
{{- if .Values.egs.metricsIngestion.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.egs.metricsIngestion.service.name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.egs.metricsIngestion.labels }}
  labels:
  {{ toYaml .Values.egs.metricsIngestion.labels | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.egs.metricsIngestion.service.port }}
      targetPort: 8080
  selector:
  {{- if .Values.egs.metricsIngestion.labels }}
  {{ toYaml .Values.egs.metricsIngestion.labels | nindent 4 }}
  {{- end }}
{{- end }} 