apiVersion: v1
kind: ConfigMap
metadata:
  name: namespace-labels-config
  namespace: {{ .Release.Namespace }}
data:
  labels: |-
    {{- toJson .Values.global.namespaceConfig.labels | nindent 4 }}
  annotations: |-
    {{- toJson .Values.global.namespaceConfig.annotations | nindent 4 }}
