apiVersion: v1
kind: Secret
metadata:
  name: egs-controller-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  LINODE_TOKEN: {{ .Values.egs.inventory.linodeToken | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: egs-controller-config
  namespace: {{ .Release.Namespace }}
data:
  DEFAULT_DYNAMIC_TOTAL_GPU_NODES: "{{ .Values.egs.inventory.defaultDynamicTotalGpuNodes }}"
  MAX_NODE_POOL_COUNT: "{{ .Values.egs.gprManager.maxNodePoolCount }}"
  ENABLE_DYNAMIC_NODE: "{{ .Values.egs.gprManager.enableDynamicNode }}"
  ENABLE_WEBHOOKS: "true"
  QMGR_GRPC_ADDRESS: "{{ .Values.egs.queueManager.service.name }}:{{ .Values.egs.queueManager.service.port }}"
  INVMGR_GRPC_ADDRESS: "{{ .Values.egs.inventory.service.name }}:{{ .Values.egs.inventory.service.port }}"
  QMGR_CHECK_PERIOD: "{{ .Values.egs.gprManager.qmgrCheckPeriod }}"
  MAX_DELAYED_COUNT: "{{ .Values.egs.gprManager.maxDelayedCount }}"
  WAIT_TIME_REFRESH_PERIOD: "{{ .Values.egs.gprManager.refreshWaitTimeInterval }}"
  LINODE_TOKEN: "{{ .Values.egs.inventory.linodeToken }}"