apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr1
  namespace: ai-ran                #REPLACE with onboarded namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: davecomery/gpu-stress-test:latest
        resources:
          limits:
            nvidia.com/gpu: 1