apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pricing-service
  name: kubetally-pricing-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing-service
  strategy: {}
  template:
    metadata:
      labels:
        app: pricing-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - image:  '{{ .Values.global.imageRegistry }}/{{.Values.kubetally.pricingService.image}}:{{.Values.kubetally.pricingService.tag}}'
          imagePullPolicy: {{.Values.kubetally.pricingService.imagePullPolicy}}
          name: pricing-service
          securityContext:
            runAsUser: 65536
            runAsGroup: 65536
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: Production
            - name: PRICE_DATABASE_ADDR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresAddr
            - name: PRICE_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresPort
            - name: PRICE_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresUser
            - name: PRICE_DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresPassword
            - name: PRICE_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresDB
            - name: DATABASE_SSL_MODE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresSslmode
            - name: PORT
              value: "8088"
            - name: PROM_HOST
              value: {{ .Values.global.kubeTally.prometheusUrl }}
            - name: CONTROLLER_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      securityContext:
        runAsUser: 65536               # Non-root user
        runAsGroup: 65536              # Non-root group
        runAsNonRoot: true             # Ensure the container does not run as root
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: {{ .Values.kubetally.imagePullSecretName }}
      tolerations:
        - operator: "Exists"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubetally-pricing-updater
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.global.kubeTally.pricingUpdaterSchedule }}"
  startingDeadlineSeconds: 120
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            prometheus.io/port: '9999'
            prometheus.io/scrape: 'true'
        spec:
          containers:
            - name: pricing-updater
              securityContext:
                runAsUser: 65536
                runAsGroup: 65536
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
              imagePullPolicy: {{ .Values.kubetally.chargeUpdater.imagePullPolicy }}
              image: '{{ .Values.global.imageRegistry }}/{{ .Values.kubetally.chargeUpdater.image}}:{{ .Values.kubetally.chargeUpdater.tag }}'
              env:
                - name: APP_ENV
                  value: Production
                - name: PRICE_DATABASE_ADDR
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                      key: postgresAddr
                - name: PRICE_DATABASE_PORT
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                      key: postgresPort
                - name: PRICE_DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                      key: postgresUser
                - name: PRICE_DATABASE_PASS
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                      key: postgresPassword
                - name: PRICE_DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                      key: postgresDB
                - name: DATABASE_SSL_MODE
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                      key: postgresSslmode
                - name: NUM_AWS_PULL_WORKERS
                  value: "{{.Values.global.kubeTally.priceUpdaterWorkers}}"
                - name: JOB_MODE
                  value: PRICE_UPDATE
                - name: PROMETHEUS_ENDPOINT
                  value: {{ .Values.global.kubeTally.prometheusUrl }}
                - name: CLOUD_PROVIDERS
                  value: {{ .Values.global.kubeTally.pricingUpdaterCloudProviders }}
                - name: CONTROLLER_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
          securityContext:
            runAsUser: 65536               # Non-root user
            runAsGroup: 65536              # Non-root group
            runAsNonRoot: true             # Ensure the container does not run as root
            seccompProfile:
              type: RuntimeDefault
          imagePullSecrets:
            - name: {{ .Values.kubetally.imagePullSecretName }}
          restartPolicy: Never
      backoffLimit: 4
      ttlSecondsAfterFinished: 86400


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: report-service
  name: kubetally-report
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  strategy: {}
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
        - name: report-service
          securityContext:
            runAsUser: 65536
            runAsGroup: 65536
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          imagePullPolicy: {{ .Values.kubetally.kubeTallyReport.imagePullPolicy }}
          image: '{{ .Values.global.imageRegistry }}/{{ .Values.kubetally.kubeTallyReport.image}}:{{ .Values.kubetally.kubeTallyReport.tag }}'
          env:
            - name: APP_ENV
              value: production
            - name: PRICE_DATABASE_ADDR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresAddr
            - name: PRICE_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresPort
            - name: PRICE_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresUser
            - name: PRICE_DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresPassword
            - name: PRICE_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresDB
            - name: DATABASE_SSL_MODE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresSslmode
            - name: HOURS_AGO
              value: '{{ .Values.global.kubeTally.dataProcessingHoursAgo }}'
            - name: PROMETHEUS_ENDPOINT
              value: {{ .Values.global.kubeTally.prometheusUrl }}
            - name: NUM_AWS_PULL_WORKERS
              value: "{{.Values.global.kubeTally.priceUpdaterWorkers}}"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      securityContext:
        runAsUser: 65536               # Non-root user
        runAsGroup: 65536              # Non-root group
        runAsNonRoot: true             # Ensure the container does not run as root
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: {{ .Values.kubetally.imagePullSecretName }}
      tolerations:
        - operator: "Exists"


---
apiVersion: batch/v1
kind: Job
metadata:
  name: kubetally-pricing-updater-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-1"
spec:
  template:
    metadata:
      annotations:
        prometheus.io/port: '9999'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: pricing-updater
          securityContext:
            runAsUser: 65536
            runAsGroup: 65536
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          imagePullPolicy: {{ .Values.kubetally.chargeUpdater.imagePullPolicy }}
          image: '{{ .Values.global.imageRegistry }}/{{ .Values.kubetally.chargeUpdater.image}}:{{ .Values.kubetally.chargeUpdater.tag }}'
          env:
            - name: APP_ENV
              value: Production
            - name: PRICE_DATABASE_ADDR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresAddr
            - name: PRICE_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresPort
            - name: PRICE_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresUser
            - name: PRICE_DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresPassword
            - name: PRICE_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresDB
            - name: DATABASE_SSL_MODE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.kubeTally.postgresSecretName | default "kubetally-db-credentials" }}  # Uses the provided or default secret name
                  key: postgresSslmode
            - name: NUM_AWS_PULL_WORKERS
              value: "{{.Values.global.kubeTally.priceUpdaterWorkers}}"
            - name: JOB_MODE
              value: PRICE_UPDATE
            - name: PROMETHEUS_ENDPOINT
              value: {{ .Values.global.kubeTally.prometheusUrl }}
            - name: CONTROLLER_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
      securityContext:
        runAsUser: 65536               # Non-root user
        runAsGroup: 65536              # Non-root group
        runAsNonRoot: true             # Ensure the container does not run as root
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: {{ .Values.kubetally.imagePullSecretName }}
      restartPolicy: Never
  ttlSecondsAfterFinished: 86400