---
apiVersion: v1
kind: Service
metadata:
  name: kubetally-pricing-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: pricing-service
  ports:
    - name: http
      port: 30001
      targetPort: 8088
  type: {{.Values.global.kubeTally.priceServiceType}}
