#!/bin/bash

# Target repository configuration
# Docker Hub: REPO="docker.io/username"
# Private registry (Nexus): REPO="registry.example.com" (e.g., kubeslice.aveshalabs.io)
REPO="kubeslice.aveshalabs.io"

# Images to push (update from helm-chart-images.txt generated by airgap-image-pull.sh)
IMAGES=(
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/alpine-k8s:1.0.1"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/alpine-k8s:1.22.9"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/brancz-kube-rbac-proxy:v0.18.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/cmd-admission-webhook-k8s:1.7.3"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/cmd-exclude-prefixes-k8s:1.5.5"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/cmd-forwarder-kernel:1.0.9"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/cmd-nsc:1.5.14"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/cmd-nsc-init:1.5.9"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/cmd-nse-vl3:1.0.6"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/cmd-nsmgr:1.5.7"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/cmd-registry-k8s:1.5.6"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/dns:0.1.4"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/egs-agent:1.0.3"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/egs-core-apis:1.14.4"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/egs-gpu-agent:1.0.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/envoygateway:v1.0.3"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/envoyproxy-distroless:1.30.4"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/gateway-certs-generator:0.8.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/gpr-manager:1.14.3"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/gw-sidecar:1.0.5"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/inventory-manager:1.14.3"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kserve-controller:v0.14.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kserve-huggingfaceserver:v0.14.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kserve-lgbserver:v0.14.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kserve-modelmesh-controller:v0.12.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kserve-paddleserver:v0.14.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kserve-pmmlserver:v0.14.1"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kserve-sklearnserver:v0.14.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kserve-storage-initializer:v0.14.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kserve-xgbserver:v0.14.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kube-aiops-operator:1.15.3"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kubebuilder-kube-rbac-proxy:0.18.2"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kubeslice-api-gw-ent-egs:1.15.4"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kubeslice-controller-ent-egs:1.15.4"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kubeslice-router-sidecar:1.4.6"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kubeslice-ui-ent-egs:1.15.4"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kubeslice-ui-proxy:1.12.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kubeslice-ui-v2-ent-egs:1.15.4"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/kubetally-report:1.13.5"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/metrics-server:v0.6.2"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/netops:0.2.2"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/nvidia-tritonserver:23.04-py3"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/nvidia-tritonserver:23.05-py3"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/openvino-model_server:2022.2"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/openvpn-client.alpine:1.0.4"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/openvpn-server.alpine:1.0.4"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/price-updater:1.12.3"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/pricing-service:1.13.3"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/proxyv2:1.16.1"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/pytorch-torchserve:0.7.1-cpu"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/pytorch-torchserve-kfs:0.9.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/queue-manager:1.13.3"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/seldonio-mlserver:1.3.2"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/seldonio-mlserver:1.5.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/sig-storage-csi-node-driver-registrar:v2.8.1"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/slicegw-edge:1.0.6"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/spiffe-csi-driver:0.2.7"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/spiffe-spire-controller-manager:0.2.3"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/spire-agent:1.9.2"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/spire-server:1.9.2"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/tensorflow-serving:2.6.2"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/wait-for-it:1.0.2"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/wireguard-client.alpine:1.0.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/wireguard-server.alpine:1.0.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/worker-installer:1.10.0"
"harbor.saas1.smart-scaler.io/avesha/aveshasystems/worker-operator-ent-egs:1.15.4"
)

DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run) DRY_RUN=true; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

function pull_tag_and_push_image() {
    local IMAGE="$1"
    local TAGGED_IMAGE
    
    # Detect registry type based on REPO format
    if [[ "$REPO" == *"/"* ]]; then
        # Docker Hub with username (e.g., docker.io/myuser) → use image name only
        TAGGED_IMAGE="$REPO/$(basename "$IMAGE")"
    else
        # Private registry (e.g., kubeslice.aveshalabs.io) → preserve path structure
        TAGGED_IMAGE="$REPO/$(echo $IMAGE | cut -d '/' -f 3-)"
    fi
    
    echo "Pulling $IMAGE"
    if ! $DRY_RUN; then
        docker pull $IMAGE
    fi
    
    echo "Tagging $IMAGE as $TAGGED_IMAGE"
    if ! $DRY_RUN; then
        docker tag $IMAGE $TAGGED_IMAGE
        docker push $TAGGED_IMAGE
    fi
}

# Loop through the images, pull, tag, and push them to the repository
for IMAGE in "${IMAGES[@]}"; do
    pull_tag_and_push_image "$IMAGE"
done
