apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fake-kwok-gpu-device-plugin
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - watch
