apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fake-kwok-gpu-device-plugin
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: fake-kwok-gpu-device-plugin
subjects:
  - kind: ServiceAccount
    name: kwok-gpu-device-plugin
    namespace: "{{ .Release.Namespace }}"
