{{- $root := . }}
{{- with .Values.upstreamAuthority.disk }}
{{- if and (eq (.enabled | toString) "true") (eq (.secret.create | toString) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret.name }}
  namespace: spire
data:
  {{- with .secret.data }}
  tls.crt: {{ .certificate }}
  tls.key: {{ .key }}
  {{- if ne .bundle ""}}
  bundle.crt: {{ .bundle }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
