{{- $secretName := "kserve-webhook-server-cert" }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $caCertEnc := "" -}}
{{- $tlsCertEnc := "" -}}
{{- $tlsKeyEnc := "" -}}
{{- if not $existingSecret }}
# generate a new ca & certificate
{{- $ca := genCA "kserve-admission-controller-ca" 3650 -}}
{{- $caCertEnc = $ca.Cert | b64enc -}}
{{- $cn := printf "kserve-webhook-server-service" -}}
{{- $altName1 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc.cluster.local" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca -}}
{{- $tlsCertEnc = $cert.Cert | b64enc -}}
{{- $tlsKeyEnc = $cert.Key | b64enc -}}
{{- else }}
# Reuse existing certificates from the secret
{{- $caCertEnc = index $existingSecret.data "ca.crt" -}}
{{- $tlsCertEnc = index $existingSecret.data "tls.crt" -}}
{{- $tlsKeyEnc = index $existingSecret.data "tls.key" -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: kserve-webhook-server-cert
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ $caCertEnc }}
  tls.crt: {{ $tlsCertEnc }}
  tls.key: {{ $tlsKeyEnc }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: inferenceservice.serving.kserve.io
webhooks:
  - clientConfig:
      caBundle: {{ $caCertEnc }}
      service:
        name: kserve-webhook-server-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-serving-kserve-io-v1beta1-inferenceservice
    failurePolicy: Fail
    name: inferenceservice.kserve-webhook-server.defaulter
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices
  - clientConfig:
      caBundle: {{ $caCertEnc }}
      service:
        name: kserve-webhook-server-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-pods
    failurePolicy: Fail
    name: inferenceservice.kserve-webhook-server.pod-mutator
    sideEffects: None
    reinvocationPolicy: IfNeeded
    admissionReviewVersions: ["v1beta1"]
    objectSelector:
      matchExpressions:
        - key: serving.kserve.io/inferenceservice
          operator: Exists
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: inferenceservice.serving.kserve.io
webhooks:
  - clientConfig:
      caBundle: {{ $caCertEnc }}
      service:
        name: kserve-webhook-server-service
        namespace: {{ .Release.Namespace }}
        path: /validate-serving-kserve-io-v1beta1-inferenceservice
    failurePolicy: Fail
    name: inferenceservice.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferenceservices

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: trainedmodel.serving.kserve.io
webhooks:
  - clientConfig:
      caBundle: {{ $caCertEnc }}
      service:
        name: kserve-webhook-server-service
        namespace: {{ .Release.Namespace }}
        path: /validate-serving-kserve-io-v1alpha1-trainedmodel
    failurePolicy: Fail
    name: trainedmodel.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - trainedmodels

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: inferencegraph.serving.kserve.io
webhooks:
  - clientConfig:
      caBundle: {{ $caCertEnc }}
      service:
        name: kserve-webhook-server-service
        namespace: {{ .Release.Namespace }}
        path: /validate-serving-kserve-io-v1alpha1-inferencegraph
    failurePolicy: Fail
    name: inferencegraph.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - inferencegraphs
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: clusterservingruntime.serving.kserve.io
webhooks:
  - clientConfig:
      caBundle: {{ $caCertEnc }}
      service:
        name: kserve-webhook-server-service
        namespace: {{ .Release.Namespace }}
        path: /validate-serving-kserve-io-v1alpha1-clusterservingruntime
    failurePolicy: Fail
    name: clusterservingruntime.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusterservingruntimes
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: servingruntime.serving.kserve.io
webhooks:
  - clientConfig:
      caBundle: {{ $caCertEnc }}
      service:
        name: kserve-webhook-server-service
        namespace: {{ .Release.Namespace }}
        path: /validate-serving-kserve-io-v1alpha1-servingruntime
    failurePolicy: Fail
    name: servingruntime.kserve-webhook-server.validator
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    rules:
      - apiGroups:
          - serving.kserve.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servingruntimes
