apiVersion: v1
kind: ConfigMap
metadata:
  name: aiops-config
data:
  GRAFANA_DASHBOARD_URL: {{ .Values.egs.grafanaDashboardBaseUrl }}
  PROMETHEUS_SERVICE_ENDPOINT: {{ .Values.egs.prometheusEndpoint }}
  gpu-config.yaml: |
    - type: "NVIDIA A10"
      powerThreshold: "140"
      tempThreshold: "87"
    - type: "NVIDIA A100"
      powerThreshold: "348"
      tempThreshold: "87"
    - type: "NVIDIA H100"
      powerThreshold: "609"
      tempThreshold: "87"
    - type: "NVIDIA P100"
      powerThreshold: "217"
      tempThreshold: "87"
    - type: "NVIDIA V100"
      powerThreshold: "261"
      tempThreshold: "87"
    - type: "NVIDIA Tesla T4"
      powerThreshold: "61"
      tempThreshold: "87"
    - type: "NVIDIA P4"
      powerThreshold: "65"
      tempThreshold: "87"
    - type: "NVIDIA K80"
      powerThreshold: "261"
      tempThreshold: "87"
