---
{{- if and .Values.controllerSecretName (.Values.controllerSecret.namespace) (.Values.controllerSecret.endpoint) (index .Values.controllerSecret "ca.crt") (.Values.controllerSecret.token) }}  
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controllerSecretName }}  # Use provided controllerSecretName
  namespace: kubeslice-system
data:
  {{- with .Values.controllerSecret }}
    namespace: {{ .namespace }}
    endpoint: {{ .endpoint }}
    ca.crt: {{ index . "ca.crt" }}  # Use index function to access ca.crt
    token: {{ .token }}
  {{- end }}
{{- else if .Values.controllerSecretName }}  
  # If only controllerSecretName is provided, do not create a secret, use the external one
  # Do nothing, the secret will be provided externally
{{- end }}