apiVersion: batch/v1
kind: Job
metadata:
  name: patch-nsm-mutating-webhook-pre-upgade
  namespace: {{ .Values.nsmNs }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: patch-nsm-mutating-webhook
          image: "{{ .Values.global.imageRegistry }}/alpine-k8s:1.22.9"
          command:
            - /bin/sh
            - -c
            - |
              kubectl patch mutatingwebhookconfiguration nsm-mutating-webhook-configuration --type='json' -p='[{"op": "replace", "path": "/webhooks/0/failurePolicy", "value": "Ignore"}]'
      restartPolicy: Never
      serviceAccountName: admission-webhook-sa
