---
apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-svc
  namespace: {{ .Values.nsmNs }}
  labels:
    app: kubeslice-nsm-webhook
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: kubeslice-nsm-webhook
