name: Build Binary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make binary executable
        run: chmod +x make_binary.sh

      - name: Build binary
        run: ./make_binary.sh

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: egs-installer
          path: ./egs-installer

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./egs-installer
          draft: false
          prerelease: false
