apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: nvidia-dcgm
  name: nvidia-dcgm
spec:
  ports:
    - name: gpu-metrics
      port: 9400
      protocol: TCP
      targetPort: 9400
    - name: dcgm-hostengine
      port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    app: nvidia-dcgm-exporter
  type: ClusterIP
